### ISSUE TITLE
Payment add

### ISSUE THREAD

**Issue by YashikaWick** [LalithK90/labManagement#47]
![payment](https://user-images.githubusercontent.com/37634652/102081347-1831b900-3e36-11eb-87b3-fd1b64384a82.JPG)

http://localhost:8080/payment/add

**Comment by LalithK90** [comment]
Sure

this is not an issue, 
according to logic -> if there should be a sample that was already completed if the sample is not complete or reject, there is no payment

if you want to check payment 
1. add sample (cashier)
2. accept that sample(lab)
3. enter result (lab)
4. go to  http://localhost:8080/payment/needToPay
5. can view payment form

**Comment by YashikaWick** [comment]
In 3rd step( Enter results), add and update both directs to update page.
What should I fix? html or controller?

**Comment by LalithK90** [comment]
I do not remember all process this project so could u plz add image of view and URL which were used
