### ISSUE TITLE
Income report error & labTestName.html chart

### ISSUE THREAD

**Issue by YashikaWick** [LalithK90/labManagement#72]
**1. Income report amount is not giving correct output. Always show cash amount as 400000 and credit card amount as 0.**
![payment report](https://user-images.githubusercontent.com/37634652/114615902-dae61680-9cc3-11eb-9937-fc8a798fc2b0.JPG)

![payment data](https://user-images.githubusercontent.com/37634652/114615952-eafdf600-9cc3-11eb-96ce-1f741af1fbd1.JPG)

**2. Need help on labTestName.html line 141**

**Comment by LalithK90** [comment]
plz check now 

issue resolved branch is 

[issue-72-Income_report_error_labTestName_html_chart](https://github.com/LalithK90/labManagement/tree/issue-72-Income_report_error_labTestName_html_chart?rgh-link-date=2021-04-13T20%3A23%3A46Z)

**Comment by YashikaWick** [comment]
It is not commited I think

**Comment by LalithK90** [comment]
now merge with master
